export const products = [
  {
    id: 1,
    name: "Pique de Surubi entero, Pique de Surubi entero",
    state: 0,
    category_id: 1,
    subcategory_id: 7,
    photo: "https://source.unsplash.com/1600x900/?food,breakfast",
    price: 25,
  },
  {
    id: 2,
    name: "Vino Tinto",
    state: 1,
    category_id: 1,
    subcategory_id: 7,
    photo: "https://source.unsplash.com/1600x900/?drink,juice",
    price: 25,
  },
  {
    id: 3,
    name: "Filete Asado",
    state: 2,
    category_id: 1,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?food,lauch",
    price: 25,
  },
  {
    id: 4,
    name: "Sopa de Maní",
    state: 0,
    category_id: 1,
    subcategory_id: 2,
    photo: "https://source.unsplash.com/1600x900/?food,breakfast",
    price: 22,
  },
  {
    id: 5,
    name: "Taquiña",
    state: 1,
    category_id: 1,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?food,dinner",
    price: 22,
  },
  {
    id: 6,
    name: "Mesa 1",
    state: 0,
    category_id: 2,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?food,lauch",
    price: 15,
  },
  {
    id: 7,
    name: "Vino Tinto",
    state: 2,
    category_id: 2,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?food,lauch",
    price: 15,
  },
  {
    id: 8,
    name: "Filete Asado",
    state: 0,
    category_id: 2,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?food,lauch",
    price: 15,
  },
  {
    id: 9,
    name: "Sopa de Maní",
    state: 1,
    category_id: 2,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?food,lauch",
    price: 10,
  },
  {
    id: 10,
    name: "Taquiña",
    state: 1,
    category_id: 2,
    subcategory_id: 7,
    photo: "https://source.unsplash.com/1600x900/?food,lauch",
    price: 10,
  },
  {
    id: 11,
    name: "Mesa 1",
    state: 2,
    category_id: 3,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?food,dinner",
    price: 12,
  },
  {
    id: 12,
    name: "Vino Tinto",
    state: 1,
    category_id: 3,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?food,dinner",
    price: 12,
  },
  {
    id: 13,
    name: "Filete Asado",
    state: 0,
    category_id: 3,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?food,dinner",
    price: 12,
  },
  {
    id: 14,
    name: "Sopa de Maní",
    state: 0,
    category_id: 3,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?food,dinner",
    price: 12,
  },
  {
    id: 15,
    name: "Taquiña",
    state: 1,
    category_id: 3,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?food,dinner",
    price: 8,
  },
  {
    id: 16,
    name: "Mesa 1",
    state: 0,
    category_id: 4,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?food,lauch",
    price: 8,
  },
  {
    id: 17,
    name: "Vino Tinto",
    state: 2,
    category_id: 4,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?food,lauch",
    price: 8,
  },
  {
    id: 18,
    name: "Filete Asado",
    state: 2,
    category_id: 4,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?food,lauch",
    price: 35,
  },
  {
    id: 19,
    name: "Sopa de Maní",
    state: 0,
    category_id: 4,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?food,lauch",
    price: 35,
  },
  {
    id: 20,
    name: "Taquiña",
    state: 1,
    category_id: 4,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?food,lauch",
    price: 35,
  },
  {
    id: 21,
    name: "Pique de Surubi entero",
    state: 0,
    category_id: 5,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?drink,juice",
    price: 35,
  },
  {
    id: 22,
    name: "Vino Tinto",
    state: 1,
    category_id: 5,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?drink,juice",
    price: 35,
  },
  {
    id: 23,
    name: "Filete Asado",
    state: 0,
    category_id: 5,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?drink,juice",
    price: 35,
  },
  {
    id: 24,
    name: "Sopa de Maní",
    state: 2,
    category_id: 5,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?drink,juice",
    price: 35,
  },
  {
    id: 25,
    name: "Taquiña",
    state: 0,
    category_id: 5,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?drink,juice",
    price: 20,
  },
  {
    id: 26,
    name: "Coca Cola",
    state: 0,
    category_id: 5,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?drink,juice",
    price: 20,
  },
  {
    id: 27,
    name: "Mesa 7",
    state: 1,
    category_id: 5,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?drink,juice",
    price: 20,
  },
  {
    id: 28,
    name: "Mesa 8",
    state: 0,
    category_id: 5,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?drink,juice",
    price: 20,
  },
  {
    id: 29,
    name: "Mesa 9",
    state: 2,
    category_id: 5,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?drink,juice",
    price: 20,
  },
  {
    id: 30,
    name: "Mesa 10",
    state: 2,
    category_id: 5,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?drink,juice",
    price: 20,
  },
  {
    id: 31,
    name: "Mesa 11",
    state: 2,
    category_id: 5,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?drink,beer",
    price: 20,
  },
  {
    id: 32,
    name: "Mesa 12",
    state: 2,
    category_id: 5,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?drink,juice",
    price: 20,
  },
  {
    id: 33,
    name: "Pizza",
    state: 2,
    category_id: 5,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?drink,juice",
    price: 20,
  },
  {
    id: 34,
    name: "Mesa 14",
    state: 2,
    category_id: 5,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?drink,beer",
    price: 20,
  },
  {
    id: 35,
    name: "Mesa 15",
    state: 2,
    category_id: 5,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?drink,spry",
    price: 20,
  },
  {
    id: 36,
    name: "Pique de Surubi entero",
    state: 1,
    category_id: 5,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?drink,juice",
    price: 20,
  },
  {
    id: 37,
    name: "Mesa 17",
    state: 3,
    category_id: 5,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?drink,juice",
    price: 20,
  },
  {
    id: 38,
    name: "Mesa 18",
    state: 0,
    category_id: 5,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?drink,juice",
    price: 20,
  },
  {
    id: 39,
    name: "Omelett",
    state: 0,
    category_id: 5,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?drink,juice",
    price: 20,
  },
  {
    id: 40,
    name: "Mesa 20",
    state: 1,
    category_id: 5,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?drink,juice",
    price: 20,
  },
  {
    id: 41,
    name: "Mesa 21",
    state: 0,
    category_id: 5,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?drink,juice",
    price: 20,
  },
  {
    id: 42,
    name: "Pique de Surubi entero",
    state: 1,
    category_id: 5,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?drink,juice",
    price: 20,
  },
  {
    id: 43,
    name: "Mesa 23",
    state: 1,
    category_id: 5,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?drink,juice",
    price: 20,
  },
  {
    id: 44,
    name: "Mesa 24",
    state: 2,
    category_id: 5,
    subcategory_id: null,
    photo: "https://source.unsplash.com/1600x900/?drink,juice",
    price: 20,
  },
];
